# Docker Compose file for Vapor
#
# Learn more: https://docs.docker.com/compose/reference/
#
#   Build images: docker compose build
#      Start app: docker compose up app
# Run migrations: docker compose run migrate
#       Stop all: docker compose down (add -v to wipe db)
#
version: '3'

volumes:
  db_data:
  pgdata:

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DATABASE_URL: "postgres://postgres@db:5432/devon"
  POSTGRES_USER: postgres
  POSTGRES_DB: devon
  API_KEY: ${API_KEY}
  SECRET: ${SECRET}
  
  
services:
  app:
    image: chatgpt-server:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    ports:
      - '8080:8080'
    depends_on:
      - db
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
    
  db:
    image: postgres:16
    restart: always
    environment:
      <<: *shared_environment
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  migrate:
    image: chatgpt-server:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0
      
  revert:
    image: chatgpt-server:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0

